version: '3'

services:
  web:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      ConnectionStrings_DapperUniversity: "Server=db;Port=5432;Database=postgres;User ID=postgres;Password=P@ssw0rd!;"

  flyway:
    build: ./Migrations
    command: -url=jdbc:postgresql://db/postgres -user=postgres -password=P@ssw0rd! migrate
    depends_on:
      - db

  db:
    image: postgres
    environment:
        POSTGRES_PASSWORD: "P@ssw0rd!"
