version: '3'

services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db

  flyway:
    build: ./Migrations
    command: -url=jdbc:postgresql://db/postgres -user=postgres -password=P@ssw0rd! migrate
    depends_on:
      - db

  db:
    image: postgres
    environment:
        POSTGRES_PASSWORD: "P@ssw0rd!"
